const treinos = {
    tipos: {
        peito: "",
        costas: "",
        biceps: "",
        triceps: "",
        ombro: "",
        anterior: "",
        posterior: "",
        panturrilha: "",
        abdominais: "",
        aerobico: ""
    },
    peito: [
        { id: 1, show: false, exercicio: "Crucifixo c/ Halteres", series: 3, reps: 15, obs: "" },
        { id: 2, show: false, exercicio: "Peck Deck", series: 3, reps: 15, obs: "" },
        { id: 3, show: false, exercicio: "Supino Reto", series: 3, reps: 15, obs: "" },
        { id: 4, show: false, exercicio: "Supino Reto Maq.", series: 3, reps: 15, obs: "" },
        { id: 5, show: false, exercicio: "Supino Inclinado", series: 3, reps: 15, obs: "" },
        { id: 6, show: false, exercicio: "Supino Declinado", series: 3, reps: 15, obs: "" },
    ],
    costas: [
        { id: 7, show: false, exercicio: "Barra Fixa", series: 3, reps: 15, obs: "" },
        { id: 8, show: false, exercicio: "Puxador Alto", series: 3, reps: 15, obs: "" },
        { id: 9, show: false, exercicio: "Puxador Convergente", series: 3, reps: 15, obs: "" },
        { id: 10, show: false, exercicio: "Remada Curvada", series: 3, reps: 15, obs: "" },
        { id: 11, show: false, exercicio: "Remada Sentada", series: 3, reps: 15, obs: "" },
        { id: 12, show: false, exercicio: "Remada Unilateral", series: 3, reps: 15, obs: "" },
        { id: 13, show: false, exercicio: "Remada Maq.", series: 3, reps: 15, obs: "" },
        { id: 14, show: false, exercicio: "Lev. Terra", series: 3, reps: 15, obs: "" },
        { id: 15, show: false, exercicio: "Pulldown", series: 3, reps: 15, obs: "" },
    ],
    biceps: [
        { id: 16, show: false, exercicio: "Rosca Alternada", series: 3, reps: 15, obs: "" },
        { id: 17, show: false, exercicio: "Rosca Concentrada", series: 3, reps: 15, obs: "" },
        { id: 18, show: false, exercicio: "Rosca Direta", series: 3, reps: 15, obs: "" },
        { id: 19, show: false, exercicio: "Rosca Martelo", series: 3, reps: 15, obs: "" },
        { id: 20, show: false, exercicio: "Rosca Scott", series: 3, reps: 15, obs: "" },
    ],
    triceps: [
        { id: 21, show: false, exercicio: "Tríceps Francês", series: 3, reps: 15, obs: "" },
        { id: 22, show: false, exercicio: "Tríceps Mergulho", series: 3, reps: 15, obs: "" },
        { id: 23, show: false, exercicio: "Tríceps Barra Polia", series: 3, reps: 15, obs: "" },
        { id: 24, show: false, exercicio: "Tríceps Corda Polia", series: 3, reps: 15, obs: "" },
        { id: 25, show: false, exercicio: "Tríceps Testa", series: 3, reps: 15, obs: "" },
        { id: 26, show: false, exercicio: "Coice", series: 3, reps: 15, obs: "" },
    ],
    ombro: [
        { id: 27, show: false, exercicio: "Desenvolvimento", series: 3, reps: 15, obs: "" },
        { id: 28, show: false, exercicio: "Desenv. Arnold", series: 3, reps: 15, obs: "" },
        { id: 29, show: false, exercicio: "Elevação Lateral", series: 3, reps: 15, obs: "" },
        { id: 30, show: false, exercicio: "Elevação Lat. Maq.", series: 3, reps: 15, obs: "" },
        { id: 31, show: false, exercicio: "Elevação Frontal", series: 3, reps: 15, obs: "" },
        { id: 32, show: false, exercicio: "Remada Alta", series: 3, reps: 15, obs: "" },
        { id: 33, show: false, exercicio: "Encolhimento", series: 3, reps: 15, obs: "" },
        { id: 34, show: false, exercicio: "Crucifixo Inverso", series: 3, reps: 15, obs: "" },
    ],
    anterior: [
        { id: 35, show: false, exercicio: "Agachamento Livre", series: 3, reps: 15, obs: "" },
        { id: 36, show: false, exercicio: "Agachamento Barra", series: 3, reps: 15, obs: "" },
        { id: 37, show: false, exercicio: "Agachamento Guiado", series: 3, reps: 15, obs: "" },
        { id: 38, show: false, exercicio: "Avanço", series: 3, reps: 15, obs: "" },
        { id: 39, show: false, exercicio: "Cadeira Adutora", series: 3, reps: 15, obs: "" },
        { id: 40, show: false, exercicio: "Cadeira Extensora", series: 3, reps: 15, obs: "" },
        { id: 41, show: false, exercicio: "Flexão Quadril", series: 3, reps: 15, obs: "" },
        { id: 42, show: false, exercicio: "Hack", series: 3, reps: 15, obs: "" },
        { id: 43, show: false, exercicio: "Hack Pendular", series: 3, reps: 15, obs: "" },
        { id: 44, show: false, exercicio: "Leg Press", series: 3, reps: 15, obs: "" },
        { id: 45, show: false, exercicio: "Leg Press Unilateral", series: 3, reps: 15, obs: "" },
    ],
    posterior: [
        { id: 46, show: false, exercicio: "Agachamento Sumô", series: 3, reps: 15, obs: "" },
        { id: 47, show: false, exercicio: "Agach. Sumô Maq.", series: 3, reps: 15, obs: "" },
        { id: 48, show: false, exercicio: "Abd. de Quadril", series: 3, reps: 15, obs: "" },
        { id: 49, show: false, exercicio: "Cadeira Flexora", series: 3, reps: 15, obs: "" },
        { id: 50, show: false, exercicio: "Cadeira Abdutora", series: 3, reps: 15, obs: "" },
        { id: 51, show: false, exercicio: "Elevação Pélvica", series: 3, reps: 15, obs: "" },
        { id: 52, show: false, exercicio: "Extensão de Quadril", series: 3, reps: 15, obs: "" },
        { id: 53, show: false, exercicio: "Flexora em Pé", series: 3, reps: 15, obs: "" },
        { id: 54, show: false, exercicio: "Mesa Flexora", series: 3, reps: 15, obs: "" },
        { id: 55, show: false, exercicio: "Stiff", series: 3, reps: 15, obs: "" },
    ],
    panturrilha: [
        { id: 56, show: false, exercicio: "Panturrilha em Pé", series: 3, reps: 15, obs: "" },
        { id: 57, show: false, exercicio: "Panturrilha em Pé Maq.", series: 3, reps: 15, obs: "" },
        { id: 58, show: false, exercicio: "Panturrilha Sentada", series: 3, reps: 15, obs: "" },
    ],
    abdominais: [
        { id: 59, show: false, exercicio: "Infra", series: 3, reps: 15, obs: "" },
        { id: 60, show: false, exercicio: "Oblíquo", series: 3, reps: 15, obs: "" },
        { id: 61, show: false, exercicio: "Curto", series: 3, reps: 15, obs: "" },
        { id: 62, show: false, exercicio: "Remador", series: 3, reps: 15, obs: "" },
        { id: 63, show: false, exercicio: "Prancha", series: 3, reps: 15, obs: "" },
        { id: 64, show: false, exercicio: "Superman", series: 3, reps: 15, obs: "" },
    ],
    aerobico: [
        { id: 65, show: false, exercicio: "Esteira", series: 3, reps: 15, obs: "" },
        { id: 66, show: false, exercicio: "Bike", series: 3, reps: 15, obs: "" },
        { id: 67, show: false, exercicio: "Elíptico", series: 3, reps: 15, obs: "" },
        { id: 68, show: false, exercicio: "Aero Bike", series: 3, reps: 15, obs: "" },
    ]
};


export default treinos;